### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by VinceMD** [aws-quickstart/quickstart-heptio#4]
Trying to use this quick start but https://s3.amazonaws.com/quickstart-reference/heptio/latest/templates/kubernetes-cluster.template  is not accessible

**Comment by avattathil** [comment]
**Unable to reproduce**
I am able to download/access the template linked above

**Comment by VinceMD** [comment]
Interesting I can access the S3 file from the URL above but in the AWS Console, it says

> Template validation error: TemplateURL must reference a valid S3 object to which you have access.

**Comment by VinceMD** [comment]
sorry, my bad. Internal proxy
